
POST http://localhost:8000/api/predict/
Content-Type: application/json

{
    "sentences" : [
  "got adrenaline is a boy hot"

]
}



###

POST https://happy-or-pissed.onrender.com/predict
Content-Type: application/json

{
  "text":"Hey there"
}